<?php

if( ! defined('DOCROOT') )
{
    require_once '/var/www/testlab/Faye-0.0.3/unittest/bootstrap.php';
}

use \faye\core\utility as Utility;

class StringTest extends UnitTestCase
{
    function testingHypenate()
    {
        $expected = array(
            'hello-world',
            'this-is-a-string-unit-test',
        );
        
        $data = array(
            'Hello World',
            'This is a string unit test',
        );
        

        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::hyphenate($str) );
        }
    }
    
    function testingDash()
    {
        /* Hmm, something wrong. this is underscore actually. bygones! :p */
        $expected = array(
            'hello_world',
            'this_is_a_string_unit_test',
        );
        
        $data = array(
            'Hello World',
            'This is a string unit test',
        );
        
        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::dash($str) );
        }
        
    }
    
    function testingPascalize()
    {
        $expected = array(
            'HelloWorld',
            'ThisIsAStringUnitTest',
        );
        
        $data = array(
            'Hello World',
            'This is a string unit test',
        );
        
        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::pascalize($str) );
        }
    }
    
    function testingCamelize()
    {
        /* Java style */
        
        $expected = array(
            'helloWorld',
            'thisIsAStringUnitTest',
        );
        
        $data = array(
            'Hello World',
            'This is a string unit test',
        );
        
        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::camelize($str) );
        }
    }
    
    function testingSpaceSeparate()
    {
        $data = array(
            0 => 'hello_world',
            1 => 'this_is_a_string_unit_test',
            2 => 'helloWorld',
            3 => 'thisIsAStringUnitTest',
            4 => 'HelloWorld',
            5 => 'ThisIsAStringUnitTest',
            6 => 'hello-world',
            7 => 'this-is-a-string-unit-test',
        );
        
        $expected = array(
            'Hello World',
            'This Is A String Unit Test',
            'Hello World',
            'This Is A String Unit Test',
            'Hello World',
            'This Is A String Unit Test',
            'Hello World',
            'This Is A String Unit Test',
        );
        
        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::spaceSeparate($str) );
        }
    }
    
    function testingNamespaceToDirectory()
    {
        $expected = array(
            '0' => 'apps/app/controller/',
'1' => 'apps/app/controller/',
'2' => 'apps/app/controller/',
'3' => 'apps/app/controller/',
'4' => 'apps/app/controller/',
'5' => 'apps/app/controller/',
'6' => 'apps/app/controller/',
'7' => 'apps/app/model/',
'8' => 'apps/app/model/',
'9' => 'apps/app/config/',
'10' => 'apps/app/config/',
'11' => 'apps/app/config/',
'12' => 'apps/app/config/',
'13' => 'faye/',
'14' => 'faye/core/collection/',
'15' => 'faye/core/collection/',
'16' => 'faye/core/collection/',
'17' => 'faye/core/collection/',
'18' => 'faye/core/collection/',
'19' => 'faye/core/collection/',
'20' => 'faye/core/collection/',
'21' => 'faye/core/storage/',
'22' => 'faye/core/storage/',
'23' => 'faye/core/storage/',
'24' => 'faye/core/controller/',
'25' => 'faye/core/http/response/',
'26' => 'faye/core/http/response/',
'27' => 'faye/core/http/response/',
'28' => 'faye/core/http/request/',
'29' => 'faye/core/http/request/',
'30' => 'faye/core/http/request/',
'31' => 'faye/core/utility/',
'32' => 'faye/core/utility/',
'33' => 'faye/core/view/calf/',
'34' => 'faye/core/view/calf/',
'35' => 'faye/core/view/calf/',
'36' => 'faye/core/view/calf/',
'37' => 'faye/core/view/calf/parser/',
'38' => 'faye/core/view/calf/parser/',
'39' => 'faye/core/view/calf/parser/',
'40' => 'faye/core/view/calf/parser/',
'41' => 'faye/core/view/calf/parser/',
'42' => 'faye/core/view/template/',
'43' => 'faye/core/view/template/',
'44' => 'faye/core/view/template/',
'45' => 'faye/core/view/template/',
'46' => 'faye/core/view/template/',
'47' => 'faye/core/view/',
'48' => 'faye/core/database/',
'49' => 'faye/core/database/relational/query/builder/node/',
'50' => 'faye/core/database/relational/query/builder/node/',
'51' => 'faye/core/database/relational/query/builder/node/',
'52' => 'faye/core/database/relational/query/builder/node/',
'53' => 'faye/core/database/relational/query/builder/node/',
'54' => 'faye/core/database/relational/query/builder/',
'55' => 'faye/core/database/relational/query/builder/',
'56' => 'faye/core/database/relational/query/builder/',
'57' => 'faye/core/database/relational/query/builder/',
'58' => 'faye/core/database/relational/query/builder/',
'59' => 'faye/core/database/relational/entity/',
'60' => 'faye/core/database/relational/entity/',
'61' => 'faye/core/database/relational/entity/',
'62' => 'faye/core/database/relational/entity/',
'63' => 'faye/core/database/query/builder/node/',
'64' => 'faye/core/database/query/builder/node/',
'65' => 'faye/core/database/query/builder/node/',
'66' => 'faye/core/database/query/builder/node/',
'67' => 'faye/core/database/query/builder/node/',
'68' => 'faye/core/database/query/builder/node/',
'69' => 'faye/core/database/query/builder/node/',
'70' => 'faye/core/database/query/builder/node/',
'71' => 'faye/core/database/query/builder/',
'72' => 'faye/core/database/query/builder/',
'73' => 'faye/core/database/query/builder/',
'74' => 'faye/core/database/',
'75' => 'faye/core/database/entity/',
'76' => 'faye/core/database/entity/',
'77' => 'faye/core/database/entity/',
'78' => 'faye/core/database/',
'79' => 'faye/core/database/sql/',
'80' => 'faye/core/database/sql/query/builder/node/',
'81' => 'faye/core/database/sql/query/builder/node/',
'82' => 'faye/core/database/sql/query/builder/node/',
'83' => 'faye/core/database/sql/mysql/',
'84' => 'faye/core/database/sql/mysql/',
'85' => 'faye/core/database/',
'86' => 'faye/core/database/',
'87' => 'faye/core/jQuery/',
'88' => 'faye/core/jQuery/',
'89' => 'faye/core/jQuery/',
'90' => 'faye/core/jQuery/',
'91' => 'faye/core/file/',
'92' => 'faye/core/file/',
'93' => 'faye/core/file/',
'94' => 'faye/core/code/compiler/',
'95' => 'faye/core/code/compiler/',
'96' => 'faye/core/code/compiler/node/',
'97' => 'faye/core/code/compiler/',
'98' => 'faye/core/code/compiler/',
'99' => 'faye/core/code/compiler/',
'100' => 'faye/core/code/compiler/',
'101' => 'faye/core/code/generator/',
'102' => 'faye/core/exception/',
'103' => 'faye/core/exception/',
'104' => 'faye/core/model/',
'105' => 'faye/core/model/',
'106' => 'faye/core/model/',
'107' => 'faye/core/autoload/',
'108' => 'faye/core/autoload/',
'109' => 'faye/core/config/',
'110' => 'faye/core/route/',
'111' => 'faye/core/route/',
'112' => 'faye/core/route/',
'113' => 'faye/core/xml/selector/css/',
'114' => 'faye/core/xml/selector/css/',
'115' => 'faye/core/xml/selector/css/',
'116' => 'faye/core/xml/selector/css/',
'117' => 'faye/core/xml/selector/css/',
'118' => 'faye/core/xml/selector/css/',
'119' => 'faye/core/xml/selector/css/',
'120' => 'faye/core/xml/selector/css/',
'121' => 'faye/core/xml/selector/css/',
'122' => 'faye/core/xml/ui/',
'123' => 'faye/core/xml/ui/',
'124' => 'faye/core/xml/ui/',
'125' => 'faye/core/xml/ui/',
'126' => 'faye/core/xml/ui/',
'127' => 'faye/core/xml/ui/',
'128' => 'faye/core/xml/ui/',
'129' => 'faye/core/xml/ui/',
'130' => 'faye/core/xml/ui/',
'131' => 'faye/core/xml/ui/',
'132' => 'faye/core/xml/ui/',
'133' => 'faye/core/xml/ui/',
'134' => 'faye/core/xml/ui/',
'135' => 'faye/core/xml/ui/',
'136' => 'faye/core/xml/ui/',
'137' => 'faye/core/xml/ui/',
'138' => 'faye/core/xml/ui/',
'139' => 'faye/core/xml/ui/',
'140' => 'faye/core/xml/ui/',
'141' => 'faye/core/xml/html/',
'142' => 'faye/core/xml/html/',
'143' => 'faye/core/xml/html/',
'144' => 'faye/core/xml/html/',
'145' => 'faye/core/pattern/',
'146' => 'faye/core/pattern/',
'147' => 'faye/core/pattern/',
'148' => 'faye/core/pattern/',
'149' => 'faye/core/application/',
'150' => 'faye/core/application/',
'151' => ',',
'152' => 'unittest/',
'153' => 'unittest/utility/',
'154' => 'unittest/',
'155' => 'unittest/simpletest/',
'156' => 'unittest/simpletest/',
'157' => 'unittest/simpletest/',
'158' => 'unittest/simpletest/',
'159' => 'unittest/simpletest/',
'160' => 'unittest/simpletest/',
'161' => 'unittest/simpletest/',
'162' => 'unittest/simpletest/',
'163' => 'unittest/simpletest/',
'164' => 'unittest/simpletest/extensions/',
'165' => 'unittest/simpletest/extensions/testdox/',
'166' => 'unittest/simpletest/extensions/',
'167' => 'unittest/simpletest/',
'168' => 'unittest/simpletest/',
'169' => 'unittest/simpletest/',
'170' => 'unittest/simpletest/',
'171' => 'unittest/simpletest/',
'172' => 'unittest/simpletest/',
'173' => 'unittest/simpletest/',
'174' => 'unittest/simpletest/',
'175' => 'unittest/simpletest/',
'176' => 'unittest/simpletest/',
'177' => 'unittest/simpletest/',
'178' => 'unittest/simpletest/',
'179' => 'unittest/simpletest/',
'180' => 'unittest/simpletest/',
'181' => 'unittest/simpletest/',
'182' => 'unittest/simpletest/',
'183' => 'unittest/simpletest/',
'184' => 'unittest/simpletest/',
'185' => 'unittest/simpletest/',
'186' => 'unittest/simpletest/',
'187' => 'unittest/simpletest/',
'188' => 'unittest/simpletest/',
'189' => 'unittest/simpletest/',
'190' => 'unittest/simpletest/',
'191' => 'unittest/simpletest/',
'192' => 'unittest/simpletest/',
'193' => 'unittest/simpletest/test/',
'194' => 'unittest/simpletest/test/',
'195' => 'unittest/simpletest/test/',
'196' => 'unittest/simpletest/test/',
'197' => 'unittest/simpletest/test/',
'198' => 'unittest/simpletest/test/',
'199' => 'unittest/simpletest/test/',
'200' => 'unittest/simpletest/test/',
'201' => 'unittest/simpletest/test/',
'202' => 'unittest/simpletest/test/',
'203' => 'unittest/simpletest/test/',
'204' => 'unittest/simpletest/test/',
'205' => 'unittest/simpletest/test/',
'206' => 'unittest/simpletest/test/',
'207' => 'unittest/simpletest/test/',
'208' => 'unittest/simpletest/test/',
'209' => 'unittest/simpletest/test/',
'210' => 'unittest/simpletest/test/',
'211' => 'unittest/simpletest/test/',
'212' => 'unittest/simpletest/test/',
'213' => 'unittest/simpletest/test/',
'214' => 'unittest/simpletest/test/',
'215' => 'unittest/simpletest/test/',
'216' => 'unittest/simpletest/test/',
'217' => 'unittest/simpletest/test/',
'218' => 'unittest/simpletest/test/',
'219' => 'unittest/simpletest/test/',
'220' => 'unittest/simpletest/test/',
'221' => 'unittest/simpletest/test/',
'222' => 'unittest/simpletest/test/',
'223' => 'unittest/simpletest/test/',
'224' => 'unittest/simpletest/test/',
'225' => 'unittest/simpletest/test/',
'226' => 'unittest/simpletest/test/',
'227' => 'unittest/simpletest/test/',
'228' => 'unittest/simpletest/test/',
'229' => 'unittest/simpletest/test/',
'230' => 'unittest/simpletest/test/',
'231' => 'unittest/simpletest/test/',
'232' => 'unittest/simpletest/test/',
'233' => 'unittest/simpletest/test/',
'234' => 'unittest/simpletest/test/',
'235' => 'unittest/simpletest/test/',
'236' => 'unittest/simpletest/test/support/',
'237' => 'unittest/simpletest/test/support/',
'238' => 'unittest/simpletest/test/support/',
'239' => 'unittest/simpletest/test/support/',
'240' => 'unittest/simpletest/test/support/',
'241' => 'unittest/simpletest/test/',
'242' => 'unittest/simpletest/test/',
'243' => 'unittest/simpletest/',
'244' => 'unittest/simpletest/',
'245' => 'unittest/simpletest/',
'246' => 'unittest/',
            
        );
        
        $data = array(
                                    '0' => 'apps\\app\\controller\\',
'1' => 'apps\\app\\controller\\',
'2' => 'apps\\app\\controller\\',
'3' => 'apps\\app\\controller\\',
'4' => 'apps\\app\\controller\\',
'5' => 'apps\\app\\controller\\',
'6' => 'apps\\app\\controller\\',
'7' => 'apps\\app\\model\\',
'8' => 'apps\\app\\model\\',
'9' => 'apps\\app\\config\\',
'10' => 'apps\\app\\config\\',
'11' => 'apps\\app\\config\\',
'12' => 'apps\\app\\config\\',
'13' => 'faye\\',
'14' => 'faye\\core\\collection\\',
'15' => 'faye\\core\\collection\\',
'16' => 'faye\\core\\collection\\',
'17' => 'faye\\core\\collection\\',
'18' => 'faye\\core\\collection\\',
'19' => 'faye\\core\\collection\\',
'20' => 'faye\\core\\collection\\',
'21' => 'faye\\core\\storage\\',
'22' => 'faye\\core\\storage\\',
'23' => 'faye\\core\\storage\\',
'24' => 'faye\\core\\controller\\',
'25' => 'faye\\core\\http\\response\\',
'26' => 'faye\\core\\http\\response\\',
'27' => 'faye\\core\\http\\response\\',
'28' => 'faye\\core\\http\\request\\',
'29' => 'faye\\core\\http\\request\\',
'30' => 'faye\\core\\http\\request\\',
'31' => 'faye\\core\\utility\\',
'32' => 'faye\\core\\utility\\',
'33' => 'faye\\core\\view\\calf\\',
'34' => 'faye\\core\\view\\calf\\',
'35' => 'faye\\core\\view\\calf\\',
'36' => 'faye\\core\\view\\calf\\',
'37' => 'faye\\core\\view\\calf\\parser\\',
'38' => 'faye\\core\\view\\calf\\parser\\',
'39' => 'faye\\core\\view\\calf\\parser\\',
'40' => 'faye\\core\\view\\calf\\parser\\',
'41' => 'faye\\core\\view\\calf\\parser\\',
'42' => 'faye\\core\\view\\template\\',
'43' => 'faye\\core\\view\\template\\',
'44' => 'faye\\core\\view\\template\\',
'45' => 'faye\\core\\view\\template\\',
'46' => 'faye\\core\\view\\template\\',
'47' => 'faye\\core\\view\\',
'48' => 'faye\\core\\database\\',
'49' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'50' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'51' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'52' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'53' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'54' => 'faye\\core\\database\\relational\\query\\builder\\',
'55' => 'faye\\core\\database\\relational\\query\\builder\\',
'56' => 'faye\\core\\database\\relational\\query\\builder\\',
'57' => 'faye\\core\\database\\relational\\query\\builder\\',
'58' => 'faye\\core\\database\\relational\\query\\builder\\',
'59' => 'faye\\core\\database\\relational\\entity\\',
'60' => 'faye\\core\\database\\relational\\entity\\',
'61' => 'faye\\core\\database\\relational\\entity\\',
'62' => 'faye\\core\\database\\relational\\entity\\',
'63' => 'faye\\core\\database\\query\\builder\\node\\',
'64' => 'faye\\core\\database\\query\\builder\\node\\',
'65' => 'faye\\core\\database\\query\\builder\\node\\',
'66' => 'faye\\core\\database\\query\\builder\\node\\',
'67' => 'faye\\core\\database\\query\\builder\\node\\',
'68' => 'faye\\core\\database\\query\\builder\\node\\',
'69' => 'faye\\core\\database\\query\\builder\\node\\',
'70' => 'faye\\core\\database\\query\\builder\\node\\',
'71' => 'faye\\core\\database\\query\\builder\\',
'72' => 'faye\\core\\database\\query\\builder\\',
'73' => 'faye\\core\\database\\query\\builder\\',
'74' => 'faye\\core\\database\\',
'75' => 'faye\\core\\database\\entity\\',
'76' => 'faye\\core\\database\\entity\\',
'77' => 'faye\\core\\database\\entity\\',
'78' => 'faye\\core\\database\\',
'79' => 'faye\\core\\database\\sql\\',
'80' => 'faye\\core\\database\\sql\\query\\builder\\node\\',
'81' => 'faye\\core\\database\\sql\\query\\builder\\node\\',
'82' => 'faye\\core\\database\\sql\\query\\builder\\node\\',
'83' => 'faye\\core\\database\\sql\\mysql\\',
'84' => 'faye\\core\\database\\sql\\mysql\\',
'85' => 'faye\\core\\database\\',
'86' => 'faye\\core\\database\\',
'87' => 'faye\\core\\jQuery\\',
'88' => 'faye\\core\\jQuery\\',
'89' => 'faye\\core\\jQuery\\',
'90' => 'faye\\core\\jQuery\\',
'91' => 'faye\\core\\file\\',
'92' => 'faye\\core\\file\\',
'93' => 'faye\\core\\file\\',
'94' => 'faye\\core\\code\\compiler\\',
'95' => 'faye\\core\\code\\compiler\\',
'96' => 'faye\\core\\code\\compiler\\node\\',
'97' => 'faye\\core\\code\\compiler\\',
'98' => 'faye\\core\\code\\compiler\\',
'99' => 'faye\\core\\code\\compiler\\',
'100' => 'faye\\core\\code\\compiler\\',
'101' => 'faye\\core\\code\\generator\\',
'102' => 'faye\\core\\exception\\',
'103' => 'faye\\core\\exception\\',
'104' => 'faye\\core\\model\\',
'105' => 'faye\\core\\model\\',
'106' => 'faye\\core\\model\\',
'107' => 'faye\\core\\autoload\\',
'108' => 'faye\\core\\autoload\\',
'109' => 'faye\\core\\config\\',
'110' => 'faye\\core\\route\\',
'111' => 'faye\\core\\route\\',
'112' => 'faye\\core\\route\\',
'113' => 'faye\\core\\xml\\selector\\css\\',
'114' => 'faye\\core\\xml\\selector\\css\\',
'115' => 'faye\\core\\xml\\selector\\css\\',
'116' => 'faye\\core\\xml\\selector\\css\\',
'117' => 'faye\\core\\xml\\selector\\css\\',
'118' => 'faye\\core\\xml\\selector\\css\\',
'119' => 'faye\\core\\xml\\selector\\css\\',
'120' => 'faye\\core\\xml\\selector\\css\\',
'121' => 'faye\\core\\xml\\selector\\css\\',
'122' => 'faye\\core\\xml\\ui\\',
'123' => 'faye\\core\\xml\\ui\\',
'124' => 'faye\\core\\xml\\ui\\',
'125' => 'faye\\core\\xml\\ui\\',
'126' => 'faye\\core\\xml\\ui\\',
'127' => 'faye\\core\\xml\\ui\\',
'128' => 'faye\\core\\xml\\ui\\',
'129' => 'faye\\core\\xml\\ui\\',
'130' => 'faye\\core\\xml\\ui\\',
'131' => 'faye\\core\\xml\\ui\\',
'132' => 'faye\\core\\xml\\ui\\',
'133' => 'faye\\core\\xml\\ui\\',
'134' => 'faye\\core\\xml\\ui\\',
'135' => 'faye\\core\\xml\\ui\\',
'136' => 'faye\\core\\xml\\ui\\',
'137' => 'faye\\core\\xml\\ui\\',
'138' => 'faye\\core\\xml\\ui\\',
'139' => 'faye\\core\\xml\\ui\\',
'140' => 'faye\\core\\xml\\ui\\',
'141' => 'faye\\core\\xml\\html\\',
'142' => 'faye\\core\\xml\\html\\',
'143' => 'faye\\core\\xml\\html\\',
'144' => 'faye\\core\\xml\\html\\',
'145' => 'faye\\core\\pattern\\',
'146' => 'faye\\core\\pattern\\',
'147' => 'faye\\core\\pattern\\',
'148' => 'faye\\core\\pattern\\',
'149' => 'faye\\core\\application\\',
'150' => 'faye\\core\\application\\',
'151' => ',',
'152' => 'unittest\\',
'153' => 'unittest\\utility\\',
'154' => 'unittest\\',
'155' => 'unittest\\simpletest\\',
'156' => 'unittest\\simpletest\\',
'157' => 'unittest\\simpletest\\',
'158' => 'unittest\\simpletest\\',
'159' => 'unittest\\simpletest\\',
'160' => 'unittest\\simpletest\\',
'161' => 'unittest\\simpletest\\',
'162' => 'unittest\\simpletest\\',
'163' => 'unittest\\simpletest\\',
'164' => 'unittest\\simpletest\\extensions\\',
'165' => 'unittest\\simpletest\\extensions\\testdox\\',
'166' => 'unittest\\simpletest\\extensions\\',
'167' => 'unittest\\simpletest\\',
'168' => 'unittest\\simpletest\\',
'169' => 'unittest\\simpletest\\',
'170' => 'unittest\\simpletest\\',
'171' => 'unittest\\simpletest\\',
'172' => 'unittest\\simpletest\\',
'173' => 'unittest\\simpletest\\',
'174' => 'unittest\\simpletest\\',
'175' => 'unittest\\simpletest\\',
'176' => 'unittest\\simpletest\\',
'177' => 'unittest\\simpletest\\',
'178' => 'unittest\\simpletest\\',
'179' => 'unittest\\simpletest\\',
'180' => 'unittest\\simpletest\\',
'181' => 'unittest\\simpletest\\',
'182' => 'unittest\\simpletest\\',
'183' => 'unittest\\simpletest\\',
'184' => 'unittest\\simpletest\\',
'185' => 'unittest\\simpletest\\',
'186' => 'unittest\\simpletest\\',
'187' => 'unittest\\simpletest\\',
'188' => 'unittest\\simpletest\\',
'189' => 'unittest\\simpletest\\',
'190' => 'unittest\\simpletest\\',
'191' => 'unittest\\simpletest\\',
'192' => 'unittest\\simpletest\\',
'193' => 'unittest\\simpletest\\test\\',
'194' => 'unittest\\simpletest\\test\\',
'195' => 'unittest\\simpletest\\test\\',
'196' => 'unittest\\simpletest\\test\\',
'197' => 'unittest\\simpletest\\test\\',
'198' => 'unittest\\simpletest\\test\\',
'199' => 'unittest\\simpletest\\test\\',
'200' => 'unittest\\simpletest\\test\\',
'201' => 'unittest\\simpletest\\test\\',
'202' => 'unittest\\simpletest\\test\\',
'203' => 'unittest\\simpletest\\test\\',
'204' => 'unittest\\simpletest\\test\\',
'205' => 'unittest\\simpletest\\test\\',
'206' => 'unittest\\simpletest\\test\\',
'207' => 'unittest\\simpletest\\test\\',
'208' => 'unittest\\simpletest\\test\\',
'209' => 'unittest\\simpletest\\test\\',
'210' => 'unittest\\simpletest\\test\\',
'211' => 'unittest\\simpletest\\test\\',
'212' => 'unittest\\simpletest\\test\\',
'213' => 'unittest\\simpletest\\test\\',
'214' => 'unittest\\simpletest\\test\\',
'215' => 'unittest\\simpletest\\test\\',
'216' => 'unittest\\simpletest\\test\\',
'217' => 'unittest\\simpletest\\test\\',
'218' => 'unittest\\simpletest\\test\\',
'219' => 'unittest\\simpletest\\test\\',
'220' => 'unittest\\simpletest\\test\\',
'221' => 'unittest\\simpletest\\test\\',
'222' => 'unittest\\simpletest\\test\\',
'223' => 'unittest\\simpletest\\test\\',
'224' => 'unittest\\simpletest\\test\\',
'225' => 'unittest\\simpletest\\test\\',
'226' => 'unittest\\simpletest\\test\\',
'227' => 'unittest\\simpletest\\test\\',
'228' => 'unittest\\simpletest\\test\\',
'229' => 'unittest\\simpletest\\test\\',
'230' => 'unittest\\simpletest\\test\\',
'231' => 'unittest\\simpletest\\test\\',
'232' => 'unittest\\simpletest\\test\\',
'233' => 'unittest\\simpletest\\test\\',
'234' => 'unittest\\simpletest\\test\\',
'235' => 'unittest\\simpletest\\test\\',
'236' => 'unittest\\simpletest\\test\\support\\',
'237' => 'unittest\\simpletest\\test\\support\\',
'238' => 'unittest\\simpletest\\test\\support\\',
'239' => 'unittest\\simpletest\\test\\support\\',
'240' => 'unittest\\simpletest\\test\\support\\',
'241' => 'unittest\\simpletest\\test\\',
'242' => 'unittest\\simpletest\\test\\',
'243' => 'unittest\\simpletest\\',
'244' => 'unittest\\simpletest\\',
'245' => 'unittest\\simpletest\\',
'246' => 'unittest\\',
        );
        
        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::namespaceToDirectory($str)  );
        }
    }
    
    function testingDirectoryToNamespace()
    {
        $data = array(
            '0' => 'apps/app/controller/',
'1' => 'apps/app/controller/',
'2' => 'apps/app/controller/',
'3' => 'apps/app/controller/',
'4' => 'apps/app/controller/',
'5' => 'apps/app/controller/',
'6' => 'apps/app/controller/',
'7' => 'apps/app/model/',
'8' => 'apps/app/model/',
'9' => 'apps/app/config/',
'10' => 'apps/app/config/',
'11' => 'apps/app/config/',
'12' => 'apps/app/config/',
'13' => 'faye/',
'14' => 'faye/core/collection/',
'15' => 'faye/core/collection/',
'16' => 'faye/core/collection/',
'17' => 'faye/core/collection/',
'18' => 'faye/core/collection/',
'19' => 'faye/core/collection/',
'20' => 'faye/core/collection/',
'21' => 'faye/core/storage/',
'22' => 'faye/core/storage/',
'23' => 'faye/core/storage/',
'24' => 'faye/core/controller/',
'25' => 'faye/core/http/response/',
'26' => 'faye/core/http/response/',
'27' => 'faye/core/http/response/',
'28' => 'faye/core/http/request/',
'29' => 'faye/core/http/request/',
'30' => 'faye/core/http/request/',
'31' => 'faye/core/utility/',
'32' => 'faye/core/utility/',
'33' => 'faye/core/view/calf/',
'34' => 'faye/core/view/calf/',
'35' => 'faye/core/view/calf/',
'36' => 'faye/core/view/calf/',
'37' => 'faye/core/view/calf/parser/',
'38' => 'faye/core/view/calf/parser/',
'39' => 'faye/core/view/calf/parser/',
'40' => 'faye/core/view/calf/parser/',
'41' => 'faye/core/view/calf/parser/',
'42' => 'faye/core/view/template/',
'43' => 'faye/core/view/template/',
'44' => 'faye/core/view/template/',
'45' => 'faye/core/view/template/',
'46' => 'faye/core/view/template/',
'47' => 'faye/core/view/',
'48' => 'faye/core/database/',
'49' => 'faye/core/database/relational/query/builder/node/',
'50' => 'faye/core/database/relational/query/builder/node/',
'51' => 'faye/core/database/relational/query/builder/node/',
'52' => 'faye/core/database/relational/query/builder/node/',
'53' => 'faye/core/database/relational/query/builder/node/',
'54' => 'faye/core/database/relational/query/builder/',
'55' => 'faye/core/database/relational/query/builder/',
'56' => 'faye/core/database/relational/query/builder/',
'57' => 'faye/core/database/relational/query/builder/',
'58' => 'faye/core/database/relational/query/builder/',
'59' => 'faye/core/database/relational/entity/',
'60' => 'faye/core/database/relational/entity/',
'61' => 'faye/core/database/relational/entity/',
'62' => 'faye/core/database/relational/entity/',
'63' => 'faye/core/database/query/builder/node/',
'64' => 'faye/core/database/query/builder/node/',
'65' => 'faye/core/database/query/builder/node/',
'66' => 'faye/core/database/query/builder/node/',
'67' => 'faye/core/database/query/builder/node/',
'68' => 'faye/core/database/query/builder/node/',
'69' => 'faye/core/database/query/builder/node/',
'70' => 'faye/core/database/query/builder/node/',
'71' => 'faye/core/database/query/builder/',
'72' => 'faye/core/database/query/builder/',
'73' => 'faye/core/database/query/builder/',
'74' => 'faye/core/database/',
'75' => 'faye/core/database/entity/',
'76' => 'faye/core/database/entity/',
'77' => 'faye/core/database/entity/',
'78' => 'faye/core/database/',
'79' => 'faye/core/database/sql/',
'80' => 'faye/core/database/sql/query/builder/node/',
'81' => 'faye/core/database/sql/query/builder/node/',
'82' => 'faye/core/database/sql/query/builder/node/',
'83' => 'faye/core/database/sql/mysql/',
'84' => 'faye/core/database/sql/mysql/',
'85' => 'faye/core/database/',
'86' => 'faye/core/database/',
'87' => 'faye/core/jQuery/',
'88' => 'faye/core/jQuery/',
'89' => 'faye/core/jQuery/',
'90' => 'faye/core/jQuery/',
'91' => 'faye/core/file/',
'92' => 'faye/core/file/',
'93' => 'faye/core/file/',
'94' => 'faye/core/code/compiler/',
'95' => 'faye/core/code/compiler/',
'96' => 'faye/core/code/compiler/node/',
'97' => 'faye/core/code/compiler/',
'98' => 'faye/core/code/compiler/',
'99' => 'faye/core/code/compiler/',
'100' => 'faye/core/code/compiler/',
'101' => 'faye/core/code/generator/',
'102' => 'faye/core/exception/',
'103' => 'faye/core/exception/',
'104' => 'faye/core/model/',
'105' => 'faye/core/model/',
'106' => 'faye/core/model/',
'107' => 'faye/core/autoload/',
'108' => 'faye/core/autoload/',
'109' => 'faye/core/config/',
'110' => 'faye/core/route/',
'111' => 'faye/core/route/',
'112' => 'faye/core/route/',
'113' => 'faye/core/xml/selector/css/',
'114' => 'faye/core/xml/selector/css/',
'115' => 'faye/core/xml/selector/css/',
'116' => 'faye/core/xml/selector/css/',
'117' => 'faye/core/xml/selector/css/',
'118' => 'faye/core/xml/selector/css/',
'119' => 'faye/core/xml/selector/css/',
'120' => 'faye/core/xml/selector/css/',
'121' => 'faye/core/xml/selector/css/',
'122' => 'faye/core/xml/ui/',
'123' => 'faye/core/xml/ui/',
'124' => 'faye/core/xml/ui/',
'125' => 'faye/core/xml/ui/',
'126' => 'faye/core/xml/ui/',
'127' => 'faye/core/xml/ui/',
'128' => 'faye/core/xml/ui/',
'129' => 'faye/core/xml/ui/',
'130' => 'faye/core/xml/ui/',
'131' => 'faye/core/xml/ui/',
'132' => 'faye/core/xml/ui/',
'133' => 'faye/core/xml/ui/',
'134' => 'faye/core/xml/ui/',
'135' => 'faye/core/xml/ui/',
'136' => 'faye/core/xml/ui/',
'137' => 'faye/core/xml/ui/',
'138' => 'faye/core/xml/ui/',
'139' => 'faye/core/xml/ui/',
'140' => 'faye/core/xml/ui/',
'141' => 'faye/core/xml/html/',
'142' => 'faye/core/xml/html/',
'143' => 'faye/core/xml/html/',
'144' => 'faye/core/xml/html/',
'145' => 'faye/core/pattern/',
'146' => 'faye/core/pattern/',
'147' => 'faye/core/pattern/',
'148' => 'faye/core/pattern/',
'149' => 'faye/core/application/',
'150' => 'faye/core/application/',
'151' => ',',
'152' => 'unittest/',
'153' => 'unittest/utility/',
'154' => 'unittest/',
'155' => 'unittest/simpletest/',
'156' => 'unittest/simpletest/',
'157' => 'unittest/simpletest/',
'158' => 'unittest/simpletest/',
'159' => 'unittest/simpletest/',
'160' => 'unittest/simpletest/',
'161' => 'unittest/simpletest/',
'162' => 'unittest/simpletest/',
'163' => 'unittest/simpletest/',
'164' => 'unittest/simpletest/extensions/',
'165' => 'unittest/simpletest/extensions/testdox/',
'166' => 'unittest/simpletest/extensions/',
'167' => 'unittest/simpletest/',
'168' => 'unittest/simpletest/',
'169' => 'unittest/simpletest/',
'170' => 'unittest/simpletest/',
'171' => 'unittest/simpletest/',
'172' => 'unittest/simpletest/',
'173' => 'unittest/simpletest/',
'174' => 'unittest/simpletest/',
'175' => 'unittest/simpletest/',
'176' => 'unittest/simpletest/',
'177' => 'unittest/simpletest/',
'178' => 'unittest/simpletest/',
'179' => 'unittest/simpletest/',
'180' => 'unittest/simpletest/',
'181' => 'unittest/simpletest/',
'182' => 'unittest/simpletest/',
'183' => 'unittest/simpletest/',
'184' => 'unittest/simpletest/',
'185' => 'unittest/simpletest/',
'186' => 'unittest/simpletest/',
'187' => 'unittest/simpletest/',
'188' => 'unittest/simpletest/',
'189' => 'unittest/simpletest/',
'190' => 'unittest/simpletest/',
'191' => 'unittest/simpletest/',
'192' => 'unittest/simpletest/',
'193' => 'unittest/simpletest/test/',
'194' => 'unittest/simpletest/test/',
'195' => 'unittest/simpletest/test/',
'196' => 'unittest/simpletest/test/',
'197' => 'unittest/simpletest/test/',
'198' => 'unittest/simpletest/test/',
'199' => 'unittest/simpletest/test/',
'200' => 'unittest/simpletest/test/',
'201' => 'unittest/simpletest/test/',
'202' => 'unittest/simpletest/test/',
'203' => 'unittest/simpletest/test/',
'204' => 'unittest/simpletest/test/',
'205' => 'unittest/simpletest/test/',
'206' => 'unittest/simpletest/test/',
'207' => 'unittest/simpletest/test/',
'208' => 'unittest/simpletest/test/',
'209' => 'unittest/simpletest/test/',
'210' => 'unittest/simpletest/test/',
'211' => 'unittest/simpletest/test/',
'212' => 'unittest/simpletest/test/',
'213' => 'unittest/simpletest/test/',
'214' => 'unittest/simpletest/test/',
'215' => 'unittest/simpletest/test/',
'216' => 'unittest/simpletest/test/',
'217' => 'unittest/simpletest/test/',
'218' => 'unittest/simpletest/test/',
'219' => 'unittest/simpletest/test/',
'220' => 'unittest/simpletest/test/',
'221' => 'unittest/simpletest/test/',
'222' => 'unittest/simpletest/test/',
'223' => 'unittest/simpletest/test/',
'224' => 'unittest/simpletest/test/',
'225' => 'unittest/simpletest/test/',
'226' => 'unittest/simpletest/test/',
'227' => 'unittest/simpletest/test/',
'228' => 'unittest/simpletest/test/',
'229' => 'unittest/simpletest/test/',
'230' => 'unittest/simpletest/test/',
'231' => 'unittest/simpletest/test/',
'232' => 'unittest/simpletest/test/',
'233' => 'unittest/simpletest/test/',
'234' => 'unittest/simpletest/test/',
'235' => 'unittest/simpletest/test/',
'236' => 'unittest/simpletest/test/support/',
'237' => 'unittest/simpletest/test/support/',
'238' => 'unittest/simpletest/test/support/',
'239' => 'unittest/simpletest/test/support/',
'240' => 'unittest/simpletest/test/support/',
'241' => 'unittest/simpletest/test/',
'242' => 'unittest/simpletest/test/',
'243' => 'unittest/simpletest/',
'244' => 'unittest/simpletest/',
'245' => 'unittest/simpletest/',
'246' => 'unittest/',
            
        );
        
        $expected = array(
                                    '0' => 'apps\\app\\controller\\',
'1' => 'apps\\app\\controller\\',
'2' => 'apps\\app\\controller\\',
'3' => 'apps\\app\\controller\\',
'4' => 'apps\\app\\controller\\',
'5' => 'apps\\app\\controller\\',
'6' => 'apps\\app\\controller\\',
'7' => 'apps\\app\\model\\',
'8' => 'apps\\app\\model\\',
'9' => 'apps\\app\\config\\',
'10' => 'apps\\app\\config\\',
'11' => 'apps\\app\\config\\',
'12' => 'apps\\app\\config\\',
'13' => 'faye\\',
'14' => 'faye\\core\\collection\\',
'15' => 'faye\\core\\collection\\',
'16' => 'faye\\core\\collection\\',
'17' => 'faye\\core\\collection\\',
'18' => 'faye\\core\\collection\\',
'19' => 'faye\\core\\collection\\',
'20' => 'faye\\core\\collection\\',
'21' => 'faye\\core\\storage\\',
'22' => 'faye\\core\\storage\\',
'23' => 'faye\\core\\storage\\',
'24' => 'faye\\core\\controller\\',
'25' => 'faye\\core\\http\\response\\',
'26' => 'faye\\core\\http\\response\\',
'27' => 'faye\\core\\http\\response\\',
'28' => 'faye\\core\\http\\request\\',
'29' => 'faye\\core\\http\\request\\',
'30' => 'faye\\core\\http\\request\\',
'31' => 'faye\\core\\utility\\',
'32' => 'faye\\core\\utility\\',
'33' => 'faye\\core\\view\\calf\\',
'34' => 'faye\\core\\view\\calf\\',
'35' => 'faye\\core\\view\\calf\\',
'36' => 'faye\\core\\view\\calf\\',
'37' => 'faye\\core\\view\\calf\\parser\\',
'38' => 'faye\\core\\view\\calf\\parser\\',
'39' => 'faye\\core\\view\\calf\\parser\\',
'40' => 'faye\\core\\view\\calf\\parser\\',
'41' => 'faye\\core\\view\\calf\\parser\\',
'42' => 'faye\\core\\view\\template\\',
'43' => 'faye\\core\\view\\template\\',
'44' => 'faye\\core\\view\\template\\',
'45' => 'faye\\core\\view\\template\\',
'46' => 'faye\\core\\view\\template\\',
'47' => 'faye\\core\\view\\',
'48' => 'faye\\core\\database\\',
'49' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'50' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'51' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'52' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'53' => 'faye\\core\\database\\relational\\query\\builder\\node\\',
'54' => 'faye\\core\\database\\relational\\query\\builder\\',
'55' => 'faye\\core\\database\\relational\\query\\builder\\',
'56' => 'faye\\core\\database\\relational\\query\\builder\\',
'57' => 'faye\\core\\database\\relational\\query\\builder\\',
'58' => 'faye\\core\\database\\relational\\query\\builder\\',
'59' => 'faye\\core\\database\\relational\\entity\\',
'60' => 'faye\\core\\database\\relational\\entity\\',
'61' => 'faye\\core\\database\\relational\\entity\\',
'62' => 'faye\\core\\database\\relational\\entity\\',
'63' => 'faye\\core\\database\\query\\builder\\node\\',
'64' => 'faye\\core\\database\\query\\builder\\node\\',
'65' => 'faye\\core\\database\\query\\builder\\node\\',
'66' => 'faye\\core\\database\\query\\builder\\node\\',
'67' => 'faye\\core\\database\\query\\builder\\node\\',
'68' => 'faye\\core\\database\\query\\builder\\node\\',
'69' => 'faye\\core\\database\\query\\builder\\node\\',
'70' => 'faye\\core\\database\\query\\builder\\node\\',
'71' => 'faye\\core\\database\\query\\builder\\',
'72' => 'faye\\core\\database\\query\\builder\\',
'73' => 'faye\\core\\database\\query\\builder\\',
'74' => 'faye\\core\\database\\',
'75' => 'faye\\core\\database\\entity\\',
'76' => 'faye\\core\\database\\entity\\',
'77' => 'faye\\core\\database\\entity\\',
'78' => 'faye\\core\\database\\',
'79' => 'faye\\core\\database\\sql\\',
'80' => 'faye\\core\\database\\sql\\query\\builder\\node\\',
'81' => 'faye\\core\\database\\sql\\query\\builder\\node\\',
'82' => 'faye\\core\\database\\sql\\query\\builder\\node\\',
'83' => 'faye\\core\\database\\sql\\mysql\\',
'84' => 'faye\\core\\database\\sql\\mysql\\',
'85' => 'faye\\core\\database\\',
'86' => 'faye\\core\\database\\',
'87' => 'faye\\core\\jQuery\\',
'88' => 'faye\\core\\jQuery\\',
'89' => 'faye\\core\\jQuery\\',
'90' => 'faye\\core\\jQuery\\',
'91' => 'faye\\core\\file\\',
'92' => 'faye\\core\\file\\',
'93' => 'faye\\core\\file\\',
'94' => 'faye\\core\\code\\compiler\\',
'95' => 'faye\\core\\code\\compiler\\',
'96' => 'faye\\core\\code\\compiler\\node\\',
'97' => 'faye\\core\\code\\compiler\\',
'98' => 'faye\\core\\code\\compiler\\',
'99' => 'faye\\core\\code\\compiler\\',
'100' => 'faye\\core\\code\\compiler\\',
'101' => 'faye\\core\\code\\generator\\',
'102' => 'faye\\core\\exception\\',
'103' => 'faye\\core\\exception\\',
'104' => 'faye\\core\\model\\',
'105' => 'faye\\core\\model\\',
'106' => 'faye\\core\\model\\',
'107' => 'faye\\core\\autoload\\',
'108' => 'faye\\core\\autoload\\',
'109' => 'faye\\core\\config\\',
'110' => 'faye\\core\\route\\',
'111' => 'faye\\core\\route\\',
'112' => 'faye\\core\\route\\',
'113' => 'faye\\core\\xml\\selector\\css\\',
'114' => 'faye\\core\\xml\\selector\\css\\',
'115' => 'faye\\core\\xml\\selector\\css\\',
'116' => 'faye\\core\\xml\\selector\\css\\',
'117' => 'faye\\core\\xml\\selector\\css\\',
'118' => 'faye\\core\\xml\\selector\\css\\',
'119' => 'faye\\core\\xml\\selector\\css\\',
'120' => 'faye\\core\\xml\\selector\\css\\',
'121' => 'faye\\core\\xml\\selector\\css\\',
'122' => 'faye\\core\\xml\\ui\\',
'123' => 'faye\\core\\xml\\ui\\',
'124' => 'faye\\core\\xml\\ui\\',
'125' => 'faye\\core\\xml\\ui\\',
'126' => 'faye\\core\\xml\\ui\\',
'127' => 'faye\\core\\xml\\ui\\',
'128' => 'faye\\core\\xml\\ui\\',
'129' => 'faye\\core\\xml\\ui\\',
'130' => 'faye\\core\\xml\\ui\\',
'131' => 'faye\\core\\xml\\ui\\',
'132' => 'faye\\core\\xml\\ui\\',
'133' => 'faye\\core\\xml\\ui\\',
'134' => 'faye\\core\\xml\\ui\\',
'135' => 'faye\\core\\xml\\ui\\',
'136' => 'faye\\core\\xml\\ui\\',
'137' => 'faye\\core\\xml\\ui\\',
'138' => 'faye\\core\\xml\\ui\\',
'139' => 'faye\\core\\xml\\ui\\',
'140' => 'faye\\core\\xml\\ui\\',
'141' => 'faye\\core\\xml\\html\\',
'142' => 'faye\\core\\xml\\html\\',
'143' => 'faye\\core\\xml\\html\\',
'144' => 'faye\\core\\xml\\html\\',
'145' => 'faye\\core\\pattern\\',
'146' => 'faye\\core\\pattern\\',
'147' => 'faye\\core\\pattern\\',
'148' => 'faye\\core\\pattern\\',
'149' => 'faye\\core\\application\\',
'150' => 'faye\\core\\application\\',
'151' => ',',
'152' => 'unittest\\',
'153' => 'unittest\\utility\\',
'154' => 'unittest\\',
'155' => 'unittest\\simpletest\\',
'156' => 'unittest\\simpletest\\',
'157' => 'unittest\\simpletest\\',
'158' => 'unittest\\simpletest\\',
'159' => 'unittest\\simpletest\\',
'160' => 'unittest\\simpletest\\',
'161' => 'unittest\\simpletest\\',
'162' => 'unittest\\simpletest\\',
'163' => 'unittest\\simpletest\\',
'164' => 'unittest\\simpletest\\extensions\\',
'165' => 'unittest\\simpletest\\extensions\\testdox\\',
'166' => 'unittest\\simpletest\\extensions\\',
'167' => 'unittest\\simpletest\\',
'168' => 'unittest\\simpletest\\',
'169' => 'unittest\\simpletest\\',
'170' => 'unittest\\simpletest\\',
'171' => 'unittest\\simpletest\\',
'172' => 'unittest\\simpletest\\',
'173' => 'unittest\\simpletest\\',
'174' => 'unittest\\simpletest\\',
'175' => 'unittest\\simpletest\\',
'176' => 'unittest\\simpletest\\',
'177' => 'unittest\\simpletest\\',
'178' => 'unittest\\simpletest\\',
'179' => 'unittest\\simpletest\\',
'180' => 'unittest\\simpletest\\',
'181' => 'unittest\\simpletest\\',
'182' => 'unittest\\simpletest\\',
'183' => 'unittest\\simpletest\\',
'184' => 'unittest\\simpletest\\',
'185' => 'unittest\\simpletest\\',
'186' => 'unittest\\simpletest\\',
'187' => 'unittest\\simpletest\\',
'188' => 'unittest\\simpletest\\',
'189' => 'unittest\\simpletest\\',
'190' => 'unittest\\simpletest\\',
'191' => 'unittest\\simpletest\\',
'192' => 'unittest\\simpletest\\',
'193' => 'unittest\\simpletest\\test\\',
'194' => 'unittest\\simpletest\\test\\',
'195' => 'unittest\\simpletest\\test\\',
'196' => 'unittest\\simpletest\\test\\',
'197' => 'unittest\\simpletest\\test\\',
'198' => 'unittest\\simpletest\\test\\',
'199' => 'unittest\\simpletest\\test\\',
'200' => 'unittest\\simpletest\\test\\',
'201' => 'unittest\\simpletest\\test\\',
'202' => 'unittest\\simpletest\\test\\',
'203' => 'unittest\\simpletest\\test\\',
'204' => 'unittest\\simpletest\\test\\',
'205' => 'unittest\\simpletest\\test\\',
'206' => 'unittest\\simpletest\\test\\',
'207' => 'unittest\\simpletest\\test\\',
'208' => 'unittest\\simpletest\\test\\',
'209' => 'unittest\\simpletest\\test\\',
'210' => 'unittest\\simpletest\\test\\',
'211' => 'unittest\\simpletest\\test\\',
'212' => 'unittest\\simpletest\\test\\',
'213' => 'unittest\\simpletest\\test\\',
'214' => 'unittest\\simpletest\\test\\',
'215' => 'unittest\\simpletest\\test\\',
'216' => 'unittest\\simpletest\\test\\',
'217' => 'unittest\\simpletest\\test\\',
'218' => 'unittest\\simpletest\\test\\',
'219' => 'unittest\\simpletest\\test\\',
'220' => 'unittest\\simpletest\\test\\',
'221' => 'unittest\\simpletest\\test\\',
'222' => 'unittest\\simpletest\\test\\',
'223' => 'unittest\\simpletest\\test\\',
'224' => 'unittest\\simpletest\\test\\',
'225' => 'unittest\\simpletest\\test\\',
'226' => 'unittest\\simpletest\\test\\',
'227' => 'unittest\\simpletest\\test\\',
'228' => 'unittest\\simpletest\\test\\',
'229' => 'unittest\\simpletest\\test\\',
'230' => 'unittest\\simpletest\\test\\',
'231' => 'unittest\\simpletest\\test\\',
'232' => 'unittest\\simpletest\\test\\',
'233' => 'unittest\\simpletest\\test\\',
'234' => 'unittest\\simpletest\\test\\',
'235' => 'unittest\\simpletest\\test\\',
'236' => 'unittest\\simpletest\\test\\support\\',
'237' => 'unittest\\simpletest\\test\\support\\',
'238' => 'unittest\\simpletest\\test\\support\\',
'239' => 'unittest\\simpletest\\test\\support\\',
'240' => 'unittest\\simpletest\\test\\support\\',
'241' => 'unittest\\simpletest\\test\\',
'242' => 'unittest\\simpletest\\test\\',
'243' => 'unittest\\simpletest\\',
'244' => 'unittest\\simpletest\\',
'245' => 'unittest\\simpletest\\',
'246' => 'unittest\\',
        );
        
        foreach( $data as $key => $str )
        {
            $this->assertEqual( $expected[$key], Utility\String::directoryToNamespace($str)  );
        }
    }
    
}
